/*********************************************************************************************************************************************************
 * Control Statements : used to alter the flow of execution of the program.
 *              Types : Decision Control(IF,IF-ELSE, IF-ElseIf ladder), Iterative Control(while, do-while, for loops), Switch Case Control, goto control.
 * 
 * > Decision control statements works on the boolean values generated by conditions.
 * > we can add multiple number of IFs in a single program and multiple operators can be used in condition domain of IF.
 * > else suite is optional.
 * > IF condition segment can result in BOOLEAN VALUE, zero or non-zero values.
 * > In a IF-ELSE IF Ladder only one of the suite of decision control statement will run.
 * > else cannot exist without if and else can only come after else, noting can exist in between them.
 * >
 * > 
 * 
 * 
 * 
************************************************************************************************************************************************************/
#include <stdio.h>

int main()
{
    int x,y;
    char ch;
    int a,b,c;
    float marks;
    //IF
    if(2|3)
    {
        printf("Hello kamal");
    }
    //IF ELSE-IF ELSE
    printf("\n Enter the charcter: ");
    scanf("%c",&ch);
    if(ch>=97 && ch<=122)
        printf("Small Case Alphabet");
    else if(ch>=65 && ch<=90)
        printf("Large case alphabets");
    else if(ch>=48 && ch<=57)
        printf("Numeric Characters");
    else
        printf("Other Special Characters");
    printf("\n--------------------------------------------------------------------");
    //IF Else
    printf("\nEnter the value of x = ");
    scanf("%d",&x);
    if(x>0)
    {
        printf("X is positive");
    }
    else
    {
        printf("X is Negetive.");
    }

    //Nested IF ELSE
    printf("\n Enter three numbers seperated with space: ");
    scanf("%d %d %d",&a,&b,&c);
    if(a>b)
    {
        if(a>c)
            printf("%d",a);
        else
            printf("%d",c);
    }
    else
    {
        if(b>c)
            printf("%d",b);
        else
            printf("%d",c);
    }
    // above code using conditional statement: 
    printf("\n%d",a>b?(a>c?a:c):(b>c?b:c));

    //IF-ELSE LADDER
    printf("\nEnter the Marks: ");
    scanf("%f", &marks);
    if(marks>90)
        printf("Grade-A");
    else
        if(marks>80)
            printf("Grade-B");
        else
            if(marks>70)
                printf("Grade-C");
            else
                printf("Grade-D");
    return 0;
}